sudo: required
dist: trusty
language: minimal
script:

notifications:
  webhooks:
    urls:
      - https://us-central1-dev-user-joelallred.cloudfunctions.net/trigger-testgen-from-cbmc
    on_success: always
    on_failure: always
    on_start: never
    on_cancel: never
    on_error: always


